### ISSUE TITLE
Inner join raises error "no current record for fetch operation" if a stored procedure depends on some table via input parameter and also has an indexed relationship with another table

### ISSUE THREAD

**Issue by gsbelarus** [FirebirdSQL/firebird#7937] opened 2023-12-31 14:22 UTC
The following query works well on Firebird 2.5, but on Firebird 5, it results in a `no current record for fetch operation` error message.

```sql
SELECT
  LAST_CARD.USR$LISTNUMBER,
  EMPL.ID,
  CARD.USR$FIRSTMOVE,
  EMPL.NAME,
  LAST_CARD.USR$BASETSALARY,
  LAST_CARD.USR$STAFFNUMBER,
  LAST_CARD.USR$TSALARY,
  LAST_CARD.USR$MSALARY,
  LAST_CARD.USR$THOURRATE,
  LAST_CARD.USR$MHOURRATE
FROM
  USR$WG_MOVEMENTLINE CARD
  LEFT JOIN GD_DOCUMENT DOC ON DOC.ID = CARD.DOCUMENTKEY
  LEFT JOIN USR$WG_P_EMPLMOVESTATE_FMK(CARD.USR$EMPLKEY, :EMPLSDATE) MOV ON MOV.FIRSTMOVEKEY = CARD.USR$FIRSTMOVE
  LEFT JOIN USR$WG_MOVEMENTLINE LAST_CARD ON LAST_CARD.DOCUMENTKEY = MOV.ID
  LEFT JOIN GD_CONTACT EMPL ON EMPL.ID = CARD.USR$EMPLKEY
WHERE
  CARD.USR$STAFFLISTPOSID = :USR$POSID
  AND
  DOC.COMPANYKEY = :COMPANY_KEY
  AND
  CARD.DOCUMENTKEY = MOV.ID
  AND
  LAST_CARD.USR$MOVEMENTTYPE <> 3
ORDER BY
  EMPL.NAME
```  
The error arises due to two conditions: `CARD.DOCUMENTKEY = MOV.ID` and `LAST_CARD.USR$MOVEMENTTYPE <> 3`. Both conditions fail because the corresponding entries are absent in the joined tables. Therefore, the conditions should be interpreted as `CARD.DOCUMENTKEY = null` and `null <> 3`, which both evaluate to `False`.

Should the query be modified as:

```sql
SELECT
  LAST_CARD.USR$LISTNUMBER,
  EMPL.ID,
  CARD.USR$FIRSTMOVE,
  EMPL.NAME,
  LAST_CARD.USR$BASETSALARY,
  LAST_CARD.USR$STAFFNUMBER,
  LAST_CARD.USR$TSALARY,
  LAST_CARD.USR$MSALARY,
  LAST_CARD.USR$THOURRATE,
  LAST_CARD.USR$MHOURRATE
FROM
  USR$WG_MOVEMENTLINE CARD
  LEFT JOIN GD_DOCUMENT DOC ON DOC.ID = CARD.DOCUMENTKEY
  LEFT JOIN USR$WG_P_EMPLMOVESTATE_FMK(CARD.USR$EMPLKEY, :EMPLSDATE) MOV ON MOV.FIRSTMOVEKEY = CARD.USR$FIRSTMOVE
  LEFT JOIN USR$WG_MOVEMENTLINE LAST_CARD ON LAST_CARD.DOCUMENTKEY = MOV.ID
  LEFT JOIN GD_CONTACT EMPL ON EMPL.ID = CARD.USR$EMPLKEY
WHERE
  CARD.USR$STAFFLISTPOSID = :USR$POSID
  AND
  DOC.COMPANYKEY = :COMPANY_KEY
  AND
  CARD.DOCUMENTKEY = COALESCE(MOV.ID, 0)
  AND
  COALESCE(LAST_CARD.USR$MOVEMENTTYPE, 0) <> 3
ORDER BY
  EMPL.NAME
```
It begins to execute correctly on Firebird 5.

Please do not suggest changing `LEFT JOIN` to `JOIN`. We require `LEFT JOIN` in this context to ensure that the server utilizes the optimal query plan. Switching to `JOIN` results in the query being ten times slower.

**Comment by dyemanov** [comment] 2023-12-31 14:35
Using `COALESCE` is one option, setting `OuterJoinConversion = false` in _firebird.conf_ is another one. Regardless, this error should not happen, so this looks like a bug anyway. Could you please show the plan?

**Comment by gsbelarus** [comment] 2024-01-03 09:00
Plan for the query which raises error (FB5):
```
PLAN SORT (JOIN (JOIN (JOIN (CARD INDEX (RDB$PRIMARY123), LAST_CARD INDEX (RDB$PRIMARY123), DOC INDEX (GD_PK_DOCUMENT)), MOV NATURAL), EMPL INDEX (GD_PK_CONTACT)))
```
Plan, when error is fixed using COALESCEs:
```
PLAN SORT (JOIN (JOIN (JOIN (JOIN (CARD INDEX (USR$_X_USR$WG_POSID), DOC INDEX (GD_PK_DOCUMENT)), MOV NATURAL), LAST_CARD INDEX (RDB$PRIMARY123)), EMPL INDEX (GD_PK_CONTACT)))
```
Plan for FB 2.5, no error, no coalesces:
```
PLAN SORT (JOIN (JOIN (JOIN (JOIN (CARD INDEX (USR$_X_USR$WG_POSID), DOC INDEX (RDB$PRIMARY105)), SORT (ML INDEX (USR$FKUSR$WG_MOVEMENTLINE284, RDB$FOREIGN870))), ML1 ORDER RDB$FOREIGN870 INDEX (USR$FKUSR$WG_MOVEMENTLINE284)), SORT (ML INDEX (USR$FKUSR$WG_MOVEMENTLINE284, RDB$FOREIGN870)))JOIN (ML1 ORDER RDB$FOREIGN870 INDEX (RDB$FOREIGN871, USR$FKUSR$WG_MOVEMENTLINE284), WT INDEX (USR$FKWG_EMPLWORKTERM290, USR$FKWG_EMPLWORKTERM280))(LAST_CARD INDEX (RDB$PRIMARY867))(EMPL INDEX (RDB$PRIMARY17)))
```

**Comment by dyemanov** [comment] 2024-01-04 10:58
I tried to recreate your example from scratch, but I see a different plan with empty tables:

SORT (JOIN (JOIN (JOIN (CARD INDEX (RDB$PRIMARY8), DOC INDEX (RDB$PRIMARY4), LAST_CARD INDEX (RDB$PRIMARY8)), MOV NATURAL), EMPL INDEX (RDB$PRIMARY7)))

Could you provide a reproducible test case (probably simplified)?

**Comment by gsbelarus** [comment] 2024-01-04 13:37
The database file is 323 GB. Let me think how to get to the simplified version of it.

**Comment by gsbelarus** [comment] 2024-01-04 16:42
@dyemanov 
[FB_5.zip](https://github.com/FirebirdSQL/firebird/files/13833277/FB_5.zip)

**Comment by dyemanov** [comment] 2024-01-05 07:04
What input parameter values should be used to reproduce?

**Comment by YRozmysl** [comment] 2024-01-05 07:33
EMPLSDATE = 05.01.2024
  USR$POSID = 1
  COMPANY_KEY = 147002705

**Comment by dyemanov** [comment] 2024-01-05 17:05
Reproduced, thanks.

**Comment by dyemanov** [comment] 2024-01-06 06:12
Simplified test query:

```sql
SELECT count(*)
FROM USR$WG_MOVEMENTLINE CARD
  JOIN USR$WG_P_EMPLMOVESTATE_FMK(CARD.USR$EMPLKEY, date '05.01.2024') MOV ON MOV.FIRSTMOVEKEY = CARD.USR$FIRSTMOVE
  JOIN USR$WG_MOVEMENTLINE LAST_CARD ON LAST_CARD.DOCUMENTKEY = MOV.ID
```

**Comment by danidummer** [comment] 2024-03-08 12:32
Only an addendum to #8036. 
The "CROSS JOIN" suggestion fails in the discontinued version 2.5.9.
I know it won't be fixed, it's ok. Only to inform about.

**Closed** 2024-03-11 07:20 UTC
Labels: component: engine, type: bug, qa: done successfully, affect-version: 3.0.11, fix-version: 6.0 Alpha 1, affect-version: 4.0.4, affect-version: 5.0 RC 2, fix-version: 5.0.1, rlsnotes60: no

**Comment by pavel-zotov** [comment] 2024-03-24 11:24
QA issue: no data sample to reproduce.
