### ISSUE TITLE
High CPU usage connect to Firebird 3 database using Firebird 4 Classic and SuperClassic service

### ISSUE THREAD

**Issue by ccy** [FirebirdSQL/firebird#7535] opened 2023-04-03 01:43 UTC
I configure `Firebird-4.0.2.2816-0-Win32` service:

* Copy `engine12.dll` from `Firebird 3.0.10` to `Firebird 4.0.2\plugins`
* Copy `msvcr100.dll` and `msvcp100.dll` from `Firebird 3.0.10` to `Firebird 4.0.2`
* Add `Engine12` support to `firebird.conf`:
`Providers = Remote,Engine13,Engine12,Loopback`
* Set `ServerMode` to `Classic` or `SuperClassic` in `firebird.conf`.

I prepare 2 databases: `fb30.fdb` and `fb40.fdb` to try.

I open 3 cmd console and use isql to establish connection to `fb40.fdb`:

    isql -u sysdba -p masterkey inet://127.0.0.1/c:/fb40.fdb
 
All 3 `isql` connections work and CPU load for `firebird.exe` processes is `0%`.  This is expected as no processing load yet.

I close all the isql connections and connect with `fb30.fdb`:

    isql -u sysdba -p masterkey inet://127.0.0.1/c:/fb30.fdb

This time I can notice the cpu usage of `firebird.exe` process boost up.  The more connection I open to `fb30.fdb`, the CPU load is higher.

This happen to Firebird 4.0 using `SuperClassic` and `Classic` mode.  It doesn't happen to `Super` mode.

**Comment by hvlad** [comment] 2023-04-06 09:28
Confirmed. The reason is that both engines uses same names for the named Windows Events.

**Comment by hvlad** [comment] 2023-04-10 18:39
Should be fixed now, check next snapshot build

**Closed** 2023-04-13 16:48 UTC
Labels: type: bug, affect-version: 4.0.0, affect-version: 5.0 Initial, fix-version: 4.0.3, fix-version: 5.0 Beta 2
