### ISSUE TITLE
Firebird 5.0 nbackup level>0 problem

### ISSUE THREAD

**Issue by virgonia** [FirebirdSQL/firebird#7581] opened 2023-05-11 02:33 UTC
R:\>nbackup -b 0 employee e50 => level 0 success.
time elapsed    1 sec
page reads      327
page writes     326

R:\>nbackup -b 1 employee e51 => level 1 failed
Cannot find record for database "employee" backup level 0 in the backup history

R:\>isql -z
ISQL Version: WI-T5.0.0.1044 Firebird 5.0 Beta 2

**Comment by hvlad** [comment] 2023-05-11 09:59
The problem is not with nbackup itself, this is an engine bug.

To reproduce

```
recreate table t7581 (id1 int, id2 int);
create index idx_t7581 on t7581(id1, id2);
insert into t7581 values (1, 1);
commit;

select * from t7581 order by id1, id2;
-- no records
select * from t7581 order by id1, id2;
         ID1          ID2
============ ============
           1            1
```

**Comment by dyemanov** [comment] 2023-05-11 11:24
Should be fixed now.

**Closed by dyemanov** 2023-05-11 11:24 UTC
Labels: component: engine, type: bug, priority: minor
