### ISSUE TITLE
Generators and replication

### ISSUE THREAD

**Issue by lwennekers** [FirebirdSQL/firebird#7264] opened 2022-08-15 12:39 UTC
I'm testing the replication function and I noticed that the generators aren't replicated. I wonder if I'm missing a setting or could it be a bug?

**Comment by dyemanov** [comment] 2022-08-15 12:47
This is by design. Generators are replicated only if the generated values were utilized by some DML command that was committed. I'd be happy to know about the real-world case where the generated values must be replicated regardless whether they were stored inside the database or not.

**Comment by dyemanov** [comment] 2022-08-15 16:30
> When the replicated database become master database, it is not possible to work without real generator values.
Why? Who cares if last N values are lost if they were not stored anywhere? The max stored value will still match the replicated generator value, so nothing gonna be broken.

**Comment by dyemanov** [comment] 2022-08-15 16:31
> Also consider that generators can be used as settings flag.

**Comment by livius2** [comment] 2022-08-15 18:58
Such setting will be realy good, someone if like, can even setup all generators to replicate. 
You can add worning about some potetntial performane problems, but i do not see such risk. 
As how replicating generator value can be more performance problem then new record with data which need to be replicated? As normally generator is incremented when new record will be abialable soon to replication, and the record itself is much bigger then generator.

**Comment by lwennekers** [comment] 2022-08-16 12:28
> > When the replicated database become master database, it is not possible to work without real generator values.
> 
> Why? Who cares if last N values are lost if they were not stored anywhere? The max stored value will still match the replicated generator value, so nothing gonna be broken.

This could become a problem if the generated value is a primary key for a table. 
By the way does it matter if I use triggers to retrieve the generator value?

**Comment by dyemanov** [comment] 2022-08-16 12:55
> This could become a problem if the generated value is a primary key for a table. 

Nope. If the new PK value was stored and committed, the generator is always replicated as well. If the PK was stored but rolled back, or not stored at all (e.g. `select gen_id() from rdb$database`), then the replica will contain neither PK nor the new generator value, but it does not break anything.

> By the way does it matter if I use triggers to retrieve the generator value?

No, it does not matter.

**Comment by aafemt** [comment] 2022-08-16 13:01
Except a strange case when "select gen_id" and "insert" are in different attachments but this is crazy anyway.

**Comment by dyemanov** [comment] 2022-08-16 13:04
BTW, what exactly Firebird version do you test? Because there was a bug #6848 which was fixed in v4.0.1.

**Comment by omachtandras** [comment] 2022-08-16 13:13
"Except a strange case when "select gen_id" and "insert" are in different **_transactions_** but this is crazy anyway."
I can imagine this at stateless applications.

**Comment by aafemt** [comment] 2022-08-16 13:16
I wrote "attachments" and that's exactly what I meant. Different transactions in single attachment are fine.

**Comment by livius2** [comment] 2022-08-16 13:38
>Nope. If the new PK value was stored and committed, the generator is always replicated as well. If the PK was stored but rolled back, or not stored at all (e.g. select gen_id() from rdb$database), then the replica will contain neither PK nor the new generator value, but it does not break anything.

How it is replicated, and **which generator**? Do you mean generator for identity field? 
I talk only about generatrors where we generate values by `GEN_ID` explicitly.
E.g. we run in application `select gen_id() from rdb$database` and we store id in new records.
We can also use `select gen_id(, 10) from rdb$database` to reserve 10 secuential records.
But how engine know that it must replicate such generator?

**Comment by aafemt** [comment] 2022-08-16 13:44
> How it is replicated, and *which generator*?

Replication of ALL generators are delayed to the first DML in the attachment. 
That's all.

**Comment by lwennekers** [comment] 2022-08-16 16:00
> BTW, what exactly Firebird version do you test? Because there was a bug #6848 which was fixed in v4.0.1.

I used v4.0.1. Going to test 4.0.2

**Comment by livius2** [comment] 2022-08-17 09:00
>Replication of ALL generators are delayed to the first DML in the attachment.
>That's all.

It looks like good solution, then probably problem was with above post about v4.0.1 instead of v4.0.2.

**Comment by lwennekers** [comment] 2022-08-29 13:46
The test is done and the generators are replicated also :) Thanks for your support

**Closed** 2022-11-09 07:08 UTC
Labels: resolution: cannot reproduce
