### ISSUE TITLE
Schema with Firebird

### ISSUE THREAD

**Issue by MarceloZaniboni** [FirebirdSQL/firebird#7820] opened 2023-10-31 14:17 UTC
We have been using Firebrid since version 1.0, and we have always evolved along with Firebrid. And today our databases have been migrating to the latest version for our clients. It is always very rewarding to be able to evolve together and take advantage of new resources.
And so, I would like to know if in the not too distant future, we will have the possibility of working with Schema, several related banks and maintaining integrity. Where is it possible to obtain data from several banks through “joins” and with the same performance as we currently have today?
This would be of great value for the scenario we have here today in development, I believe for the tool as well.

Thank you very much!
Marcelo Zaniboni

**Comment by aafemt** [comment] 2023-10-31 15:30
Big value requires big investments. It would be great if you hire someone to develop these features.

**Comment by mrotteveel** [comment] 2023-10-31 17:34
Schemas and cross-database joins are two different concepts/feature. In any case, this is a duplicate of #1113 and #1158 (there may be others)

**Closed by mrotteveel** 2023-10-31 17:34 UTC
Labels: resolution: duplicate

**Comment by asfernandes** [comment] 2023-11-01 00:30
> Big value requires big investments. It would be great if you hire someone to develop these features.

@MarceloZaniboni, @aafemt is outside sporadically contributor and does not speak for the team. I'd say it was not yet implemented because people like him, that only see problem in everything, so a complex feature will always be seem as problematic.
