### ISSUE TITLE
Firebird 4.0.2: Weird behaviour in Classic mode / linux (debian)

### ISSUE THREAD

**Issue by Koehnlein2023** [FirebirdSQL/firebird#7583] opened 2023-05-11 12:16 UTC
**Environment:**
ISQL + Server Version: LI-V4.0.2.2816 Firebird 4.0
Linux RXPROD2019 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
Firebird is startet with /etc/init.d/firebird-script (copied from /opt/fb40/misc/)
Firebird runs in Classic-Mode.

**Steps to reproduce**
**1.) Create DB**
/opt/fb40/bin/isql -user sysdba -pass masterkey
isql> create database 'fb4bug.fdb'; 
isql> commit;
isql> create table t1 (f1 smallint, f2 varchar(10)); 
isql> commit;
isql> insert into t1 (f1,f2) values (2,'B');
isql> commit;
isql> quit;
chmod 777 fb4bug.fdb

**2) Terminal-01 - Open DB** 
/opt/fb40/bin/isql localhost/3051:/usr/daten/install/FB4BUG/fb4bug.fdb -user sysdba -pass masterkey

**3) Terminal-02 - Open DB** 
/opt/fb40/bin/isql localhost/3051:/usr/daten/install/FB4BUG/fb4bug.fdb -user sysdba -pass masterkey
isql> update t1 set f2 = 'C' where f1 = 2; commit;
isql> quit;

**4) Terminal-01 (already open)**
isql> select max(f1) from t1;
=> Result = 2

**5) Terminal-02 - Open DB1** 
isql> /opt/fb40/bin/isql localhost/3051:/usr/daten/install/FB4BUG/fb4bug.fdb -user sysdba -pass masterkey
isql> update t1 set f2 = 'D' where f1 = 2; commit;
isql> quit;

**4) Terminal-01 (already open)**
isql> select max(f1) from t1;
isql> => **Result = 1  ??? (should be 2!!!)   - or do i miss something?**

The same test in ServerMode=Super works as expected.

**Comment by AlexPeshkoff** [comment] 2023-05-11 16:10
Please check current 4.0 snapshot - looks like duplicate of https://github.com/FirebirdSQL/firebird/issues/7255

**Comment by Koehnlein2023** [comment] 2023-05-12 06:34
Confirmed. Fixed in current snapshot (LI-V4.0.3.2937)
Thanks for the quick reply.

**Closed** 2023-05-12 12:30 UTC
