### ISSUE TITLE
[FB3] Some problem with concatenation

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird#7053] opened 2021-11-27 15:48 UTC
Firebird 3.0.8.33506

```
-----------

SQL> select '1' like '1' from rdb$database;
=======
<true>
SQL> select ('1' like '1') from rdb$database;
=======
<true>
SQL> select ''||('1' like '1') from rdb$database;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 17
-like
SQL> select ''||('1'='1') from rdb$database;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 16
-=
SQL> select ''||('1' is null) from rdb$database;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 17
-is
SQL>

-----------

```
"PostgreSQL 10" executes these queries without problems:

![image](https://user-images.githubusercontent.com/4594554/143687950-719e5dc7-76e6-4a97-a77f-af9e24fd0e8d.png)

**Comment by livius2** [comment] 2021-12-19 15:03
I do not suppose that explicite conversion of boolean to string should be done.
Maybe some english people can like it but think about other languages where word "true" and "false" do not exists.
E.g. in PL it is "prawda" and "fałsz". You should explicitly convert it by 

`decode(1=1, true, 'Active', false, 'Inactive', 'unknown') `

**Comment by dmitry-lipetsk** [comment] 2021-12-19 16:53
@livius2,

**SQL**
```sql
-- look to here
select '--'||cast('TRUE' as BOOLEAN)||'++' from RDB$DATABASE
```

**Output**
CONCATENATION
--TRUE++

**Comment by livius2** [comment] 2021-12-19 19:48
i do not suppose that such cast `cast('TRUE' as BOOLEAN)` is valid. What sql standard say (if it is present there)
instead of cast simpe comparision 'TRUE'='TRUE'

**Comment by mrotteveel** [comment] 2021-12-19 20:18
> i do not suppose that such cast `cast('TRUE' as BOOLEAN)` is valid. What sql standard say (if it is present there) instead of cast simpe comparision 'TRUE'='TRUE'

The `cast('TRUE' as BOOLEAN)` is valid according to the SQL standard (SQL:2016-2, section 6.13 <cast specification>. In fact, string to/from boolean is the only conversion (other than boolean to boolean) allowed.

**Comment by livius2** [comment] 2021-12-19 23:07
A little strange as `true` is a tocken like `select` `where` ..
And there is no `Cast(where to varchar(5))` ;-)

**Comment by asfernandes** [comment] 2021-12-19 23:17
> A little strange as `true` is a tocken like `select` `where` ..
> And there is no `Cast(where to varchar(5))` ;-)

No. `true` is a literal.

**Comment by livius2** [comment] 2021-12-20 07:32
Ah, this is more clear now if it is not treated as token. 
Ty Adriano. Ty  Mark for chcking this against SQL standard.

**Comment by mrotteveel** [comment] 2021-12-20 09:44
The fact `TRUE` is a reserved word (just like `NULL`) is not relevant for whether or not you can use it in a cast or not. What is relevant is whether or not it is a valid value expression, and it is.

**Comment by asfernandes** [comment] 2021-12-20 10:03
This issue is a duplicate of https://github.com/FirebirdSQL/firebird/issues/5681 and is already fixed in v4.

It will not be fixed in v3.

**Closed by asfernandes** 2021-12-20 10:03 UTC
