### ISSUE TITLE
SubQueryConversion = true --request size limit exceeded / Unsuccessful execution caused by an unavailable resource. unable to allocate memory from operating system.

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird#8231] opened 2024-08-26 07:47 UTC
Hi *!

Latest snapshot (Firebird-5.0.2.1485-0-6ef8756-windows-x64.zip) with the https://github.com/FirebirdSQL/firebird/issues/8224 fix.

This SQL returns 0 row instantly with SubQueryConversion = false, but fails with SubQueryConversion = true.
"request size limit exceeded" on one machine.
"Unsuccessful execution caused by an unavailable resource. 
unable to allocate memory from operating system." on other machine.

(looks like some kind of infinit cycle/recursion)

```
SELECT DISTINCT
    'ALTER TABLE ' || tabla.nev || ' DROP CONSTRAINT ' || tart.nev
FROM gl_obj o
    INNER JOIN gl_col c ON c.obj_id = o.id
    INNER JOIN gl_domain d ON d.id = c.mezo_id
    INNER JOIN gl_obj tart ON (tart.tipus = 'F') AND
          tart.feltetel = o.nev AND
          tart.feltetel2 CONTAINING c.nev
    INNER JOIN gl_obj tabla ON tabla.id = tart.obj_id
    INNER JOIN rdb$relation_fields rf ON rf.rdb$relation_name = o.nev AND
          rf.rdb$field_name = c.nev
WHERE d.nev STARTING WITH 'XCHAR' AND
      (NOT rf.rdb$field_source STARTING WITH 'XCHAR') AND
      EXISTS(SELECT
                 1
             FROM rdb$relation_constraints rc
             WHERE rc.rdb$constraint_name = tart.nev)   
```

I'll send you the database on request.

**Comment by dyemanov** [comment] 2024-08-26 09:12
This one was caused by the bug in my last patch, sorry for that. Fixed now.

**Closed** 2024-08-26 09:12 UTC
