### ISSUE TITLE
Run as application not specifying switch -a

### ISSUE THREAD

**Issue by hvlad** [FirebirdSQL/firebird#7637] opened 2023-06-16 12:06 UTC
On Windows Firebird server could run as a service or as an application.
In the latter case command-line switch -a should be supplied, else "nothing happens" from user POV.
Actually, process starts and immediately finishes without notifying. This often confuses new users.

I propose to run Firebird as application if it was started by user (not by SCM) without switch -a.

**Comment by aafemt** [comment] 2023-06-16 12:14
Because support for Windows XP is dropped, "-a" can be made no-op at all. The only its purpose was to avoid long timeout on StartServiceCtrlDispatcher() call before returning ERROR_FAILED_SERVICE_CONTROLLER_CONNECT which is fixed in modern Windows versions.

**Comment by hvlad** [comment] 2023-06-16 12:42
I don't think we should drop -a switch. 

As for 

> long timeout on StartServiceCtrlDispatcher()

could you point me where it is described ?

**Comment by AlexPeshkoff** [comment] 2023-06-16 13:49
@hvlad 
Is it possible to detect that firebird is started by SCM? If yes may be both switches should become optional.

**Comment by hvlad** [comment] 2023-06-16 13:58
> @hvlad Is it possible to detect that firebird is started by SCM? 

I know no direct way. I going to handle `ERROR_FAILED_SERVICE_CONTROLLER_CONNECT` error returned by `StartServiceCtrlDispatcher()` to run as application, but @aafemt say there could be long delay before return such error - and it bothers me.
On my Win10 I see no such delay. There is no mention of any such delay in [docs](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicectrldispatchera)

> If yes may be both switches should become optional.

What **both** switches ? ;) There is no special switch to run as a service, if you about it.

**Comment by aafemt** [comment] 2023-06-16 14:07
> Do you have such experience with Win7 or Vista ?

No. That's why I said that making "-a" switch obsolete is fine because WinXP is not supported anymore and the issue is fixed in later Windows. The delay could happen on WinXP which made "-a" switch useful that time, but since then it has no purpose.

**Closed** 2023-06-17 14:01 UTC
Labels: qa: cannot be tested, type: improvement, fix-version: 5.0 RC 1
