### ISSUE TITLE
Firebird 5 hang after starting remote profiling session

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird#8176] opened 2024-07-09 13:45 UTC
Starting RDB$PROFILER.START_SESSION hangs server completely. It stops responding to requests and new connections.

1. To reproduce the problem,  run Flamerobin twice and connect to probably any database (but the same database for both instances).
2. In the first Flamerobin instance, go to the system tables, right-click on e.g., RDB$FIELDS, choose "Browse data," and leave the window open.
3. In the second Flamerobin instance, execute the following query (adjust 79 to the connection ID from the first Flamerobin instance).

```SQL
SELECT RDB$PROFILER.START_SESSION('Profile without "DETAILED_REQUESTS"', NULL, 79)
FROM RDB$DATABASE;
```

I tried above session on current Firebird 5 snapshot on Windows (5.0.1.1432) 64bit, and the server hung completely.
No new connections were allowed and current connections stopped responding.

**Comment by hvlad** [comment] 2024-07-09 16:20
The more easy way to reproduce the issue.
Use database that has never run profiler session before - the problem happens when profiler creates its metadata.
Statements cache should be enabled (`MaxStatementCacheSize` <> 0)

1. start 1st isql instance against test DB and run any query, I use `select current_connection from rdb$database;` as its result will be used in next step

2. start 2nd isql instance against same DB and start profile session against attachment from 1st session: 
`SELECT RDB$PROFILER.START_SESSION('Profile', NULL, <N>) FROM RDB$DATABASE;`
where <N> is value from 1st session

Firebird is hung at this point.

**Comment by pavel-zotov** [comment] 2024-07-10 21:08
... QA notes ...
    1. On CLASSIC problem still exists: firebird hangs, although new connections to test DB are allowed (found both on 5.x and 6.x).
       One may even to run 'delete from mon$attachments' (using new ISQL session) but there is no effect: server does not perform that.
       Because of this, test currently can be run only on Super.
    2. It looks weird that user (NON-sysdba) who has necessary rights to start profiling, must be explicitly granted to access PLG* tables/views.

**Comment by pavel-zotov** [comment] 2024-07-10 21:09
PS.
Link to FB 5.x and 6.x snapshots/dumps/traces when trying to run test under Classic:
```https://drive.google.com/drive/folders/1rKtdjjrKGXuqbyldxbXUKtKvuYz086g0?usp=sharing```

**Comment by hvlad** [comment] 2024-07-11 08:22
> On CLASSIC problem still exists: firebird hangs

Could you test on Linux, please ?  I suppose this is Windows-related and completely independent bug

**Comment by pavel-zotov** [comment] 2024-07-13 06:27
Checked on 6.0.0.395-845f483-linux-x64, ServerMode = Classic: all fine, FB does not hang.
Used firebird.conf:
```
AuthServer = Srp, Win_Sspi, Legacy_Auth
BugCheckAbort = 1
ClearGTTAtRetaining = 0
ClientBatchBuffer = 131072
ConnectionIdleTimeout = 0
DefaultDBCachePages = 4K
ExtConnPoolLifeTime = 10
ExtConnPoolSize = 10
ExternalFileAccess = Full
InlineSortThreshold = 1000
IpcName = xnet_fb6x_cs
KeyHolderPlugin = fbSampleKeyHolder
MaxIdentifierByteLength = 252
MaxIdentifierCharLength = 63
MaxParallelWorkers = 8
MaxUnflushedWrites = -1
MaxUnflushedWriteTime = -1
ParallelWorkers = 1
ReadConsistency = 0
RemoteServicePort = 4700
ServerMode = Classic
SnapshotsMemSize = 64K
StatementTimeout = 300
TempCacheLimit = 128M
TempDirectories = /var/tmp/qa_2024b
TipCacheBlockSize = 4M
UseFileSystemCache = true
UserManager = Srp, Legacy_UserManager
WireCrypt = Enabled
WireCryptPlugin = ChaCha, Arc4
```

**Comment by hvlad** [comment] 2024-07-20 10:09
Reopened to fix more problems with profiler IPC

**Comment by hvlad** [comment] 2024-07-24 10:08
Should be fixed now

**Closed by hvlad** 2024-07-24 10:08 UTC
Labels: type: bug, qa: done with caveats, affect-version: 6.0 Initial, fix-version: 6.0 Alpha 1, fix-version: 5.0.1, affect-version: 5.0.0, rlsnotes60: no

**Comment by livius2** [comment] 2024-07-29 19:36
> ```sql
> RDB$PROFILER.START_SESSION
> ```

It is ok now, thanks
